version: '2'

volumes:
  compiled:

services:
  dev:
    build: .
    working_dir: /ddbes/compiled
    volumes:
      - .:/ddbes/src
      - /ddbes/src/node_modules
      - compiled:/ddbes/compiled
    command: devops/start-dev.sh
