#!/bin/ash

set -e

type=${1:-unit}
config=${CONFIG:-local}

if [ "$type" = "unit" ] || [ "$type" = "all" ]; then
  NODE_ENV=test tape '**/*.test.js' | tap-spec
fi


if [ "$type" = "integration" ] || [ "$type" = "all" ]; then
  node -r ./test/configs/$config.js test/utils/setup.js
  NODE_ENV=test tape -r ./test/configs/$config.js '**/*.test.integration.js' | tap-spec
  node -r ./test/configs/$config.js test/utils/teardown.js
fi


