#!/bin/bash

set -e
readarray -t targets < .transpile-targets

nodeVersions=("/usr/local/bin/node" "/usr/local-node-6.13.0/bin/node")

type=${1:-unit}
config=${TEST_CONFIG:-local}
PATH=$PATH:./node_modules/.bin
TAPE_BIN=./node_modules/.bin/tape

for node in "${nodeVersions[@]}"
do
  if [ "$type" = "unit" ] || [ "$type" = "all" ]; then
    NODE_ENV=test $node --harmony $TAPE_BIN 'lib/**/*.test.js' | tap-spec
  fi


  if [ "$type" = "integration" ] || [ "$type" = "all" ]; then
    $node --harmony -r ./test/configs/$config.js test/utils/setup.js
    NODE_ENV=test $node --harmony $TAPE_BIN -r ./test/configs/$config.js '**/*.test.integration.js' | tap-spec
    $node --harmony -r ./test/configs/$config.js test/utils/teardown.js
  fi   
done

